### ISSUE TITLE
Place of Birth Branching Defaults to Outside the US  - Relationships / Relatives (may be elsewhere)

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1173]
**What did you do?**

Relationships / Relatives

**What did you expect to see?**

The "place of birth" branching question defaults to born in the US.

**What did you see instead?**

The "place of birth" branching question defaults to born outside of US. Misleading because the majority of applicants will not have foreign born relatives and the question asks for State and Country which might not alert the user to the wrong selection and insert simply Ohio - United States. 

**Additional Information**

<img width="709" alt="screen shot 2018-11-17 at 9 07 51 am" src="https://user-images.githubusercontent.com/4422873/48661956-47ec1800-ea48-11e8-9c1d-1abcfb64ed9a.png">

**Comment by michaelccata** [comment]
Also noticed this in employment, seems to be an issue with all address blocks where you can choose.

<img width="829" alt="screen shot 2018-11-17 at 9 51 51 am" src="https://user-images.githubusercontent.com/4422873/48662317-81278680-ea4e-11e8-9162-5b95909676e3.png">

**Comment by el-mapache** [comment]
@michaelccata Can you reproduce this issue on a totally pristine form?

I think what might be happening is that at some point you saved the form with the 'Outside the US' radio button selected and a blank country field. Previously this caused a bug where the `In the US' radio button would be selected when the form was saved and reloaded.

This was fixed in [PR](https://github.com/18F/e-QIP-prototype/pull/1161), but if you previously selected the third option, and did not enter a country, you'll see the behavior described in this ticket.

**Comment by michaelccata** [comment]
Oh interesting, yeah I haven't had a total clean-out of my account in a long time. 

I'll see if @ryanhofdotgov can clear me out and I'll retry.

**Comment by michaelccata** [comment]
Was not able to reproduce on a clean form.
