### ISSUE TITLE
Pound signs (#####) appear in telephone extension blocks

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1186]
#1015

**Comment by ryanhofdotgov** [comment]
This wasn't ever a data issue because eApp originally had a design choice whereby placeholder text would appear in the input fields in grey text, to be a guide to users. e.g., "Enter country name", or "####" in the case of digits.

Since the archival PDF was just a reflection of the UI, all the placeholder text would still show in fields that were empty. It was not obvious that it was placeholder text and not data, due to the subtle coloring.

However, input field placeholder text was a usability design choice that was later revisited and all the placeholder text was removed. Resolved in https://github.com/18F/e-QIP-prototype/pull/1139, specifically https://github.com/18F/e-QIP-prototype/pull/1139/commits/af81cd59c8c8b169476f7f8a81bcc9a889d3e4cd
