### ISSUE TITLE
Applicant should be able to provide "Other" explanation for Foreign military service

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#1382]
## Where are you in the form?

**Section:**
Military history > Foreign military

**Question:**
During your foreign service, which organization were you serving under?

**Field:**

**Component (for example address block):**
Radio button block

## What did you see?

- [ ] Validation error
- [ ] Data not saving
- [x] Language or content issue
- [ ] Other (explain below)

Steps to reproduce: 
- Choose `other defense forces` or `other government agency`
- see that no `Specify` text field appears

## What did you expect to see?

I expected to see a `Specify` text block appear if I chose `other defense forces` or `other government agency`

## Is this error limited to just this field or others in the form?

- [x] Only relevant to just this question
- [ ] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [x] MacOS

**Browser**
- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**

**Comment by hursey013** [comment]
@ryanhofdotgov I do see `Specify` in the pdf form, but it does not appear to be a requirement in the validation matrix or XSD file - which do we use as the source of truth?

**Comment by ryanhofdotgov** [comment]
Yeah, I think you are correct @hursey013.

A point of clarification:
* "Specify" and an editable input field only appears on the PDF Nov. 2016 86 form for "Other Government Agency", not for "Other Defense Forces"

Since there's no explicit place in the SF-86 XML to store additional text if the applicant specifies "Other Government Agency", and validation matrix offers no guidance, I would mark this is a "won't fix" for the 86 since we can't submit to e-QIP. 

If same question appears in the new 85 or 85P, then we have some leeway to extend the XML.

**Comment by joshmfranklin** [comment]
@ryanhofdotgov @hursey013 this was feedback from OPM but not including it because of the XML of course makes sense. I will chat with OPM about it on our next call.

**Comment by joshmfranklin** [comment]
@ryanhofdotgov @hursey013 confirmed with OPM that this does not need to happen. We can disregard this change.
