### ISSUE TITLE
Retrieve formType from storage and include in payload to front end

### ISSUE THREAD

**Issue by gidjin** [18F/e-QIP-prototype#1429]
As part of the push to support the SF-85 as well as multiple other future forms we need to implement a way for the backend to know the form type. This information is already stored in the version deployed with secure storage; however the information is not sent to the frontend in the user information and it is unclear how to support this in the version that does not use secure storage. This will include some investigation into how this information is stored and how to retrieve it from secure storage.

NOTE This story is _**NOT**_ to figure out how to use the data in the front end, but just how to retrieve it from secure storage, send it to the frontend in the payload, and how to replicate this in the version of the app that does not use secure storage.

See #1428

**Comment by macrael** [comment]
1. The form type will be encoded in the GET /me/form response so that the UI can switch based on what form it pulls down from that api. 

2. eAgency sends a parameter called "level" when it provisions a user, that is saved in the accounts table on a "level" column. We will replicate that column and behavior here. 

3. eventually, but not for this PR, the form types that a user has been assigned (b/c there are edge cases where there can be multiple) should be set on the accounts table so we know which forms are available for a user to fill out. That will require the ability to specify multiple levels on the accounts table as well as an API for requesting different levels from the /me/form interface.

**Comment by macrael** [comment]
We'll need something to make it easy to set the level for a user in development, I think that a binary like the `unlock` tool to toggle the form would suffice. It will come with warnings that switching a user that has already partially filled out a form has data integrity issues.

**Comment by ryanhofdotgov** [comment]
What are the domain of values for `level`? To set the stage for future iterations, what ever we send to the front end should be the form type (e.g., SF-86) and a version string (e.g., 2016-11), augmenting `level` if required.

**Comment by macrael** [comment]
Is that version sent by eAgency or IM? In the eAgency API it is specified as an enum of “SF85”, “SF86”, “SF85P” but I would love if level just had the version built in instead of having two separate columns for it.

**Comment by ryanhofdotgov** [comment]
https://gsa-tts.slack.com/archives/CD1HQH1EY/p1551746167081300

**Comment by macrael** [comment]
Code is in https://github.com/18F/e-QIP-prototype/pull/1541

**Comment by macrael** [comment]
Merged
