### ISSUE TITLE
Relatives - Checkboxes/Branching

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1466]
## Where are you in the form?

**Section:**  Relationships

**Question:** Relatives
 
**Field:**  Multiple, see below

**Component (for example address block):** Accordion > Address Block, and others

## What did you see?

Checkboxes should be clearing data, but they do not leaving multiple selections chosen. See screenshots. 

`Provide the address of current employer, or provide the address of their most recent employer if not currently employed`
If you select "I don't know" the radio buttons should clear for type of addresses.
<img width="831" alt="screen shot 2019-02-21 at 3 20 58 pm" src="https://user-images.githubusercontent.com/4422873/53199778-f70f3100-35ed-11e9-9b21-1674185ca5b2.png">

`Is this relative affiliated with a foreign government, military, security, defense industry, foreign movement, or intelligence service?`
If you select "I don't know" the radio buttons should clear for yes or no and delete the followup question and text box. 
<img width="658" alt="screen shot 2019-02-21 at 3 33 09 pm" src="https://user-images.githubusercontent.com/4422873/53199812-0c845b00-35ee-11e9-82be-65834389d416.png">

- [x] Validation error
- [x] Data not saving
- [ ] Language or content issue
- [ ] Other (explain below)

## What did you expect to see?

See intended behavior above.
This feels like an issue that needs more general attention to understand what the Relatives module is doing.

## Is this error limited to just this field or others in the form?

- [ ] Only relevant to just this question
- [ ] Cross-form issue
- [x] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [x] MacOS

**Browser**
- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**

**Comment by suzubara** [comment]
@michaelccata @christopherhuii For the second item on this issue, It looks to me like the placement of the "I don't know" on this question is misleading if you answer "Yes". It seems like it should be positioned above the text area, because as-is it looks like you are answering "I don't know" to the "Describe the relative's relationship..." question.

**Comment by michaelccata** [comment]
That's a great point @suzubara 

The options should be yes/no/Idon'tknow and then the comment box should be optional. The documentation has a good breakdown.

**Comment by christopherhuii** [comment]
@michaelccata 

I wanted to follow up on `I don't know` for `Provide the address of current employer, or provide the address of their most recent employer if not currently employed`

The address fields depend on which option is selected. `In the U.S.` is selected by default if there is no value set. I can make it possible so that there is no value selected, but then there wont be any address fields.

I've made some small changes. This is what the result will look like:
![addres-idk-bug](https://user-images.githubusercontent.com/8367504/55426688-3b211a00-553a-11e9-95ac-64d4fa260f6f.gif)

I don't love this solution, but I can't quite put my finger on an alternative solution. We can't really display the correct fields unless there is an indication of what type of address it is.

**Comment by michaelccata** [comment]
I think that's a good fix @christopherhuii 
My primary concern was the appearance of two, simultaneous selections and what that might be doing on the backend. If we've cleared that default with the "I don't know" then I'm good to go.
