### ISSUE TITLE
Phone number under spouse cannot be I don't know

### ISSUE THREAD

**Issue by gidjin** [18F/e-QIP-prototype#1529]
## Where are you in the form?

**Section:**
Relationships -> Marital & relationship status -> Marital

**Question:**
Currently in a civil marriage

**Field:**
Provide this person's telephone number

**Component (for example address block):**
Phone has field I don't know which is allowed to be saved. However according to section 17.4.7 of the validation matrix the phone number is required or "Use my current telephone number" so when submitting with I don't know saved it will be rejected by e-QiP

This may also be tied into also fixing #150 

## What did you see?

- [ ] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [ X ] Other (explain below)

When submitting test case 10 to e-QiP test server the following error is show.

`SF86_5_S17-MaritalRelationshipStatus: Provide a response for "Telephone number".`

## What did you expect to see?

**I don't know** should not be a valid choice for phone number of current spouse.

## Is this error limited to just this field or others in the form?

- [ X ] Only relevant to just this question
- [ ] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [ X ] MacOS

**Browser**
- [ X ] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**
1.0.12

**Comment by suzubara** [comment]
I fixed the underlying issue here (https://github.com/18F/e-QIP-prototype/pull/1615) but have not added the "Use my current telephone number" field because a user can add multiple phone numbers, and it's not clear how their "current" number would be selected and used to populate this field. If anyone has ideas for how we might want to implement them, I think we can create a new issue to address that issue (https://github.com/18F/e-QIP-prototype/issues/150).
