### ISSUE TITLE
Banner for yes/no kickback

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#1574]
Given I my form has been returned to me for any reason
When I log back into eApp
Then I should see a banner at the top of the screen (below the progress bar) telling me why I have to reanswer certain yes/no questions
And I should not be able to dismiss this banner

![yes-no banner](https://user-images.githubusercontent.com/4196834/54699881-402ca500-4b08-11e9-9c4f-61673e909221.png)

**Comment by macrael** [comment]
This issue covers the story "As a user returning to the application after a kickback from agency personnel, I want to be reminded to address feedback in the reviewer's email and understand that other answers have been cleared and need updating because there's a lot of information that needs updating." in https://github.com/18F/e-QIP-prototype/issues/738
