### ISSUE TITLE
Accessibility - address verification modal - disable form

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#161]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2848  

When verification modal is up can we disable the rest of the form?

Users can tab through the rest of the form without interacting with the address verification modal

**Comment by bpdesigns** [comment]
validated that this is still a problem 9/25/18

1. There is no indication given to a screen reader user that this new window has opened or describe what its doing. The user can just keep clicking on things on the page. Their focus is not changed. 
2. At the bottom of the popup there are buttons for "Keep original address" and "Manually correct this address" but nothing allowing the user to exit without making one of those choices. The "exit" button is on the top right which works okay for sighted users but is out of place for screen readers. I recommend repeating the "Exit" button as the the third and last item on the list, or rephrasing " manually correct the address" so that it indicates that clicking that button will take the user back to the main page.
