### ISSUE TITLE
Permit "wet" sginature 

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#274]
In order to in be compliant with the Electronic Signature Act 15 U.S.C. 7001, Public Law 105-277 the Uniform Electronic Transaction Act, et al, applicants need to be given the option to opt out of the "Click to sign" mechanism on the waivers and instead sign in ink on printed forms ("wet" signature).

In detail, users should be able to:
* download and print the PDF versions of the release of information, medical release, credit authorization, and application certification
*  "wet" sign the forms
* scan/photograph the PDFs
* upload as attachments to the online application
* submit the application

The system should do basic validation that an attachment for all required waivers have been uploaded.

**Comment by ryanhofdotgov** [comment]
Strawman proposal:
- on the submit page, have a Yes/No button style question: "Sign waivers electronically" or "Print, sign, digitize, and upload waivers"
- "Sign waivers electronically" would be selected by default (appear in Green)
- If "Print..." option chosen, the click-to-sign waivers are removed and instead a button to download each required waiver is shown, with an adjacent upload button (i.e., don't send user to Attachment section), let them upload here.

**Comment by bpdesigns** [comment]
"Sign waivers electronically" would be selected by default (appear in Green)"
- Our  standard in eApp is to start both option in gray
<img width="636" alt="screen shot 2018-05-24 at 3 14 50 pm" src="https://user-images.githubusercontent.com/15329140/40506553-33434efa-5f65-11e8-89be-3630c1a64a3c.png">
then select green, with two different style options for content added below 
<img width="883" alt="screen shot 2018-05-24 at 3 15 31 pm" src="https://user-images.githubusercontent.com/15329140/40506987-69f34e46-5f65-11e8-83d4-3c1ff4bb0fa5.png">
<img width="872" alt="screen shot 2018-05-24 at 3 16 07 pm" src="https://user-images.githubusercontent.com/15329140/40507344-982b885a-5f65-11e8-9048-4ef76bdad3ec.png">

**Comment by ryanhofdotgov** [comment]
Here is how the existing eQIP application addresses this process:
https://nbib.opm.gov/record-providers/digitally-signed-releases/e-qip-applicant-click-to-sign-instructions.pdf

**Comment by bpdesigns** [comment]
Okay. Lets do it with the green selected for click to sign. Alternatively, this could be new pattern where we don't have those buttons at all and the default is print to sign. 

below " Please sign the releases below and submit your form
After completing this form and any attachments, you should review your answers to all questions to make sure the form is complete and accurate, and then sign and date the following certification and the attached release(s)."

We could place something like this  
"In order to in be compliant with the Electronic Signature Act 15 U.S.C. 7001, Public Law 105-277 the Uniform Electronic Transaction Act, applicants who want to opt out of the "Click to sign" mechanism can instead download <forms> (underlined and blue - see image below for styling) to sign in ink on printed forms and upload signed files."
<img width="89" alt="screen shot 2018-05-24 at 3 50 15 pm" src="https://user-images.githubusercontent.com/15329140/40510312-50c0516c-5f6a-11e8-8559-97821127141c.png">

**Comment by bpdesigns** [comment]
@ryanhofdotgov is this not needed for the Pilot anymore?

**Comment by ryanhofdotgov** [comment]
No, not strictly required any more for scope of usability study/pilot.
