### ISSUE TITLE
Evaluate USDS Forms System 

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#381]
Evaluate the USDS Forms System work-in-progress: identify overlap/gaps with our existing React components/technical approach and requirements, explore what an integration of it might look like, and what we might contribute back in a synergistic fashion.

See: 
https://github.com/usds/us-forms-system
https://github.com/usds/us-forms-system/wiki
https://github.com/mozilla-services/react-jsonschema-form
http://json-schema.org

**Comment by afeld** [comment]
[Slack conversation](https://gsa-tts.slack.com/archives/C13HJ0ZBN/p1530030278000256)

**Comment by afeld** [comment]
Had call this morning ([minimal notes](https://docs.google.com/document/d/1wl0oJ74-bKYT7s-y0rI53i5VMBIJpnH-4dHvH0Nibvc/edit)), and determined our team's best route forward here is probably trying to use some of the underlying components from the Forms System, rather than trying to make the declarative form config work for us. More information from @annekainicUSDS about using components:

---

## What components are included in us-forms-system

Right now it’s a little confusing to see what form elements are included in our library and where they come from. We should probably improve the documentation around this, but here are a few places to look for this information:

1. **Docs:** [Overview of form features](https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/available-form-features-and-usage-guidelines.md) and [available widgets](https://github.com/usds/us-forms-system/blob/master/docs/building-a-form/available-widgets.md) are 2 good places to look for examples
2. **Example form:** If you want to run through an actual form built by us-forms-system that has examples of many form elements, [this education form on Vets.gov](https://www.vets.gov/education/apply-for-education-benefits/application/1990/applicant/information) would be a good example.
3. **Code:** It’s a little hard to look at the source code and understand how the different form elements work because of the component hierarchy and how things fit together. If you want a more in-depth understanding of this, I’d recommend reading [this doc](https://github.com/usds/us-forms-system/blob/master/docs/customizing-the-library/about-the-react-component-hierarchy.md).

## Example of prefill/save-in-progress functionality

Almost all of Vets.gov’s forms include prefill/save-in-progress functionality. We decided not to include this in the MVP version of our library. So here is how Vets.gov incorporates those features:

There are 3 entrypoints to us-forms-system:

1. Top-level app component
2. createRoutes
3. createSchemaFormReducer

Ordinarily, when using us-forms-system, you include [the top-level component](https://github.com/usds/us-forms-system-starter-app/blob/master/js/components/Form.jsx#L8) (`<FormApp/>`) at your app’s top-level component. You [use the createRoutes function from us-forms-system to set all of the pages and components for each route](https://github.com/usds/us-forms-system-starter-app/blob/master/js/routes.jsx), and you [use the reducers function from us-forms-system to set your app’s state](https://github.com/usds/us-forms-system-starter-app/blob/master/js/reducers.js).

On Vets.gov, they basically overwrite these 3 entrypoints into us-forms-system by including their own wrapper components or custom routes and reducers in order to include prefill/save-in-progress functionality.

They include [a custom top-level component](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/hca/HealthCareApp.jsx#L8) (`<RoutedSavableApp/>`), and [that component renders](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/save-in-progress/RoutedSavableApp.jsx#L171) `<FormApp/>` instead.

Each page’s components are also swapped out. Where in the library, a page’s component is set within a [createRoutes](https://github.com/usds/us-forms-system/blob/master/src/js/helpers.js#L94) function, Vets.gov uses [a custom createRoutes function](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/save-in-progress/helpers.js#L11) to set their own components that incorporate prefill/save-in-progress functionality.

They also include [their own reducers](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/save-in-progress/reducers.js#L132) to include prefill/save-in-progress specific actions and state.
