### ISSUE TITLE
Only serve DAP on public-facing pages

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#390]
Guidelines for Digital Analytics Program (DAP) state:
["The Digital Analytics Program Javascript code is intended to be implemented on "public-facing" federal government webpages...and are not part of an otherwise "privileged session"](https://github.com/digital-analytics-program/gov-wide-code#appropriate-placement)

When you sign in to eApp, the DAP javascript is being loaded – it should only appear on the top-level landing page accessible to unauthenticated clients.

**Comment by afeld** [comment]
Does this app even have any public-facing pages in production?

**Comment by ryanhofdotgov** [comment]
Just the initial landing page – it has the header and button that says "Login with CAC", plus the usual "this is a government system..." banner. That Login with CAC button redirects to SAML identity provider.

**Comment by afeld** [comment]
This turns out to not be trivial, given that the entire application is a single-page app. Once DAP is loaded, the only way to ensure it's unloaded is to do a full page load. You would want this to happen right before the user logs in, but there isn't (currently) a separate page for that.

Honestly, I'm not sure only including DAP for that initial consent form is worth the effort, but happy to plug away at it if the team disagrees.

**Comment by ryanhofdotgov** [comment]
OK. I would vote for ripping it out entirely for now, since we don't want to run an external script (albeit .gov sourced) in the context of an authenticated session, especially when it isn't intended for that purpose.

We could add it back in at a later time, if it can be done on just the public page. It seems generally useful to get some usage stats that the app isn't natively collecting right now, and in theory it is (was?) an [OMB mandate](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf).
