### ISSUE TITLE
Return generic error messages in JSON, but log more specific details

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#402]
There are many places where the API (`api/http/*.go`) is returning lower level error messages to the client via the JSON response but logging a more generic error. For example:
```
service.Log.WarnError(api.InvalidJWT, err, api.LogFields{})
http.Error(w, err.Error(), http.StatusInternalServerError)
```
We want the inverse – the client should only receive a high-level error message. The server should log the lower level error (which will have more implementation details, file paths, etc.) – and the associated high-level error for context.

**Comment by macrael** [comment]
I'm taking this as a first task to help learn the stack.

**Comment by ryanhofdotgov** [comment]
https://github.com/18F/e-QIP-prototype/issues/526 is either a dup of this (or a superset), that should provide more context for this task.

**Comment by macrael** [comment]
Currently, most of our api calls that suffer errors are returning a JSON blob in the form:

```
{
    "errors": "Some description of an error"
}
```

Long term I'd like to move to something more like this for errors:
```
{
    "errors": [
        {
             "code": "INVALID_JSON",
             "message": "The request body could not be parsed as JSON"
        }
    ]
}
```

Where is the right place to track that kind of work? Does anyone know if the front end is actually using the current "errors" messages anywhere? Would it be a bad idea for me to at least insert the array now so that we have the basic structure? I don't want to start giving everything codes yet with this PR, that seems like a bigger task.

**Comment by macrael** [comment]
This is delivered by https://github.com/18F/e-QIP-prototype/pull/1082

**Comment by macrael** [comment]
Merged to develop.
