### ISSUE TITLE
proposal: make authentication more consistent

### ISSUE THREAD

**Issue by afeld** [18F/e-QIP-prototype#424]
In the current setup, the application acts differently when using an external SAML provider, versus faking one in development mode. What if we used an "external" SAML provider locally, such as [this Dockerized one](https://hub.docker.com/r/kristophjunge/test-saml-idp/)? Some benefits:

* We get to tear out a bunch of otherwise dead code
* Local development acts more like production, in that it's using an external SAML provider
* ...which also makes local debugging of SAML stuff easier

@ryanhofdotgov Thoughts?

**Comment by ryanhofdotgov** [comment]
100% – main thing is to figure out the timing of effort. I'll follow up with more details on Slack. Once in place, we can consider ripping out the simple login form all together.

**Comment by afeld** [comment]
Additional potential benefit: not needing to re-authenticate every time you refresh.

**Comment by afeld** [comment]
One potential pitfall is what we would do for deployment in cloud.gov.

**Comment by ryanhofdotgov** [comment]
If really want to do this sooner rather than later, I would definitely lean towards spending the time to set up WSO2. I think substituting in a different SAML provider only gets us so far towards replicating the environment.

For example, the WSO2 install that eApp was originally built and developed against vs the WSO2 that is currently in a different test environment, we found configuration/functional differences that necessitated code-level changes in eApp (e.g., changing a HTTP 307 redirect to an HTTP 302).

Also, when I did an initial audit of the SAML library we use (and our code around it) – I found a lot of assumptions and hard-coded stuff – I think it only works because WSO2 is ignoring certain parameters, etc. in the SAML request (ref: https://github.com/18F/e-QIP-prototype/issues/173).

That docker container you point to uses SimpleSamlPHP, which I've spent a lot of time working with, and there is a good chance it will be less forgiving with what eApp sends it and there may be more SAML problems we have yet to discover.

**Comment by afeld** [comment]
Looked over the instructions from MITRE, which use a base image I don't have access to. Ended up using [the Dockerfile and instructions provided by WSO2](https://github.com/wso2/docker-is/tree/master/dockerfiles/is), and with [a few tweaks](https://github.com/wso2/docker-is/pull/62), got it running!

![screen shot 2018-06-20 at 5 10 02 am](https://user-images.githubusercontent.com/86842/41662905-2268ca9a-7470-11e8-88a4-9fcb69f93640.png)

It's not hardened, but should be sufficient for development purposes.

**Comment by ryanhofdotgov** [comment]
We can remove 2FA, even ahead of removing basic authn.
