### ISSUE TITLE
Re-ask questions on kickback/re-submittal

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#738]
As policy, an agency wants explicit re-confirmation from the applicant on certain questions when an application has been kicked back and updated by the applicant.

Follow up with product owners on the specific questions that need to be reset/re-asked (the "yes/no" questions) 

**Action items based on the details in the workflow below:**

- [ ] Show banner when re-entry into form reminding user to make changes from agency email and that some yes/no questions will be cleared
- [ ] Clear ONLY yes/no questions previously answered `no`
- [ ] Show subsections/sections as invalid if a yes/no question within that subsection/section was cleared

Mock of UI and process:
https://drive.google.com/open?id=1YHKcCPHbm9O8wbvW6plc9FkVLDJcyZWh

Questions that need to be re-asked if answered `no`:
https://docs.google.com/spreadsheets/d/1nHJhOiQFH2k0QzQQ0HkrsllDWh6ED5yi4ytbioiLjNs/edit#gid=2087574762

Schematic
https://docs.google.com/presentation/d/1KkDicYh5jfGy5O1dJyv4JQdTdGVfw4XsqGECfsG-K9w/edit#slide=id.p

**Comment by michaelccata** [comment]
Signatures on release forms should also get reset.

**Comment by joshmfranklin** [comment]
Based on conversations with OPM we have received the go-ahead to only re-ask top level yes/no's and additional information yes/no's if the applicant had previously answered `no` to those questions. 

Mock of UI and process:
https://drive.google.com/open?id=1YHKcCPHbm9O8wbvW6plc9FkVLDJcyZWh

Questions that need to be re-asked if answered `no`:
https://docs.google.com/spreadsheets/d/1nHJhOiQFH2k0QzQQ0HkrsllDWh6ED5yi4ytbioiLjNs/edit#gid=2087574762

**Comment by michaelccata** [comment]
As a user, I want my signatures for certification and releases cleared every day to ensure that timestamp is an accurate declaration of my consent. 

As a user, if I change any of my form data, my certification and release signatures should get cleared because they are no longer valid. 

As a user returning to the application after a kickback from agency personnel, I want to be reminded to address feedback in the reviewer's email and understand that other answers have been cleared and need updating because there's a lot of information that needs updating.

As a user, I only want to re-answer top-level questions where I selected `No` because those may have changed to Yes' over time. For questions that I answered `Yes` I want to keep my previous answer and only address whether any additional events have occurred.

**Comment by macrael** [comment]
1. signatures appear to be re-required for every submission. That's not what Army seemed to think was happening on our call this week, so maybe we should check with them. But for now, this is handled implicitly. Every submission will come with new signatures. 

2. I'm working on clearing yes/no's first. 

3. How would folks like the front end to know that the form has been kicked back instead of being pristine? That would trigger the banner at the top of the screen Josh designed. I think for now it should be added to the /status call.

**Comment by suzubara** [comment]
Created https://github.com/18F/e-QIP-prototype/issues/1575 for handling these requirements:
> As a user, I want my signatures for certification and releases cleared every day to ensure that timestamp is an accurate declaration of my consent.
> As a user, if I change any of my form data, my certification and release signatures should get cleared because they are no longer valid.

**Comment by macrael** [comment]
https://github.com/18F/e-QIP-prototype/issues/1574 is handling this requirement: 
> As a user returning to the application after a kickback from agency personnel, I want to be reminded to address feedback in the reviewer's email and understand that other answers have been cleared and need updating because there's a lot of information that needs updating.

**Comment by macrael** [comment]
WIP PR: https://github.com/18F/e-QIP-prototype/pull/1612
