### ISSUE TITLE
Update UI for radio select items

### ISSUE THREAD

**Issue by line47** [18F/e-QIP-prototype#822]
When presenting 7 items or less that are a single select they should be presented as radio buttons.
This includes the yes/no branching questions.

**Why?**
Presenting items with the radio button item visible and still keeping a visually lighter button look is not as distracting for the user in addition showing the radio button clearly shows the user that the items can be selected and unselected. Also the readability increases when the radio items are stacked as opposed to fit into buttons. This would also help out immensely when printing 🖨 

**Examples of eApp questions that could use this new radio style UI**
- yes/no questions
- Select your sex
- Where you have lived - Is/was this residence
- Where you have lived - Relationship
- Select the most appropriate code to describe your school
- Provide type of degree(s)/diploma(s) received
- Provide your current marital/relationship status with regard to civil marriage, legally recognized civil union, or legally recognized domestic partnership.
- Provide this person's relationship to you
- Provide your current citizenship status
- Provide the branch of service you served in
- Provide your status
- Officer or enlisted
- Provide the type of discharge you received

**Proposed UI**
![screen shot 2018-09-18 at 1 13 05 pm](https://user-images.githubusercontent.com/1449852/45706202-a16bbf80-bb49-11e8-9be4-e6ab650c87b1.png)

**Current UI**
![screen shot 2018-09-18 at 1 50 55 pm](https://user-images.githubusercontent.com/1449852/45706235-b9434380-bb49-11e8-8a52-9a26e7740a66.png)

**Comment by ryanhofdotgov** [comment]
Regarding that last example (financial issues), it's a true check list (you can select multiple answers simultaneously), so radio buttons don't seem to apply.

**Comment by bpdesigns** [comment]
It is a list, but I would re style the list buttons to be closer to this
radio button idea and then substitute the actual round radio button for the
square checklist box.



On Sep 19, 2018, at 12:59 PM, Ryan Hofschneider <notifications@github.com>
wrote:

Regarding that last example (financial issues), it's a true check list (you
can select multiple answers simultaneously), so radio buttons don't seem to
apply.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/18F/e-QIP-prototype/issues/822#issuecomment-422879625>,
or mute the thread

**Comment by joshmfranklin** [comment]
Codepen showing updated Radio and Checkbox blocks https://codepen.io/jfrank7588/pen/vVWjYK
